database:
  host: localhost
  port: 5432
  username: postgres
  password: dart
  databaseName: dart_test
azure:
  tenantId:
  subscriptionId:
  clientId:
  clientSecret:
  resource:
  resourceGroup:
  clusterName:
  clusterURL: